import { c as create_ssr_component, e as escape, d as add_attribute, n as null_to_empty } from "../../../chunks/ssr.js";
const css = {
  code: ".login-item.svelte-17wthqx.svelte-17wthqx{display:flex;align-items:center;justify-content:center;text-align:center;font-size:13px;height:30px;align-content:center;transition:background-color 0.3s}a.svelte-17wthqx.svelte-17wthqx{color:black;text-decoration:none}.formName.svelte-17wthqx.svelte-17wthqx{width:100%;background-color:#999;height:30px}p.svelte-17wthqx.svelte-17wthqx{font:300;font-size:large;text-align:center}.login-item.svelte-17wthqx.svelte-17wthqx:hover{cursor:pointer}.container.svelte-17wthqx.svelte-17wthqx{position:relative;top:40px;margin:auto;background:#f5f5f5;width:400px;padding:10px 20px;box-shadow:0 0 10px rgba(0, 0, 0, 0.5);border-radius:4px}.login-header.svelte-17wthqx.svelte-17wthqx{display:grid;grid-template-columns:1fr 1fr;margin-bottom:20px}.signin-button.svelte-17wthqx.svelte-17wthqx{background-color:aqua}.newaccount-button.svelte-17wthqx.svelte-17wthqx{background-color:red;border:2px black;font-weight:bold;cursor:pointer}.register-form.svelte-17wthqx input.svelte-17wthqx{width:100%;padding:10px;margin-bottom:10px;border:1px solid #ddd;border-radius:4px;box-sizing:border-box}.login-form.svelte-17wthqx input.svelte-17wthqx{width:100%;padding:10px;margin-bottom:10px;border:1px solid #ddd;border-radius:4px;box-sizing:border-box}.login-button.svelte-17wthqx.svelte-17wthqx{width:100%;padding:10px;border:none;border-radius:4px;background:#d9534f;color:white;cursor:pointer}.banner.svelte-17wthqx.svelte-17wthqx{height:40px;border-radius:5px;background-image:linear-gradient(to right, #9e9e9e, #e0e0e0);box-shadow:0 4px 10px rgba(0, 0, 0, 0.2);text-align:center;position:relative;bottom:22px}.banner-text.svelte-17wthqx.svelte-17wthqx{position:relative;z-index:1;color:#333;font-size:2rem;font-weight:bold;letter-spacing:1px}.active.svelte-17wthqx.svelte-17wthqx{box-shadow:inset 0 3px 5px rgba(0, 0, 0, 0.125);transform:translateY(2px)}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let loginActive = "login-item active", registerActive;
  let email = "";
  let password = "";
  $$result.css.add(css);
  return `<div class="container svelte-17wthqx">${`<div class="banner svelte-17wthqx" data-svelte-h="svelte-oly0dq"><p class="banner-text svelte-17wthqx">Login</p></div>`} ${``} <div class="login-header svelte-17wthqx">  <a class="${escape(null_to_empty(loginActive), true) + " svelte-17wthqx"}"><div class="login-item svelte-17wthqx" data-svelte-h="svelte-mlplpi">Sign in</div></a>   <a class="${escape(null_to_empty(registerActive), true) + " svelte-17wthqx"}"><div class="login-item svelte-17wthqx" data-svelte-h="svelte-1uea6hh">New account</div></a></div> ${`<form class="login-form svelte-17wthqx"><input type="email" placeholder="E-mail" class="svelte-17wthqx"${add_attribute("value", email, 0)}> <input type="password" placeholder="Password" class="svelte-17wthqx"${add_attribute("value", password, 0)}> <button type="submit" class="login-button svelte-17wthqx" data-svelte-h="svelte-1qed880">Login</button></form>`} ${``}</div>   `;
});
export {
  Page as default
};
